// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kqgudwgxxggslmurmfgt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtxZ3Vkd2d4eGdnc2xtdXJtZmd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MzkwNDIsImV4cCI6MjA2NDAxNTA0Mn0._dDOGi_um_lomxizZEjcJNLprEowmIDt2cjpuwMpP54";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);